# Generated by Django 2.2.7 on 2019-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('run', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono_contacto', models.CharField(max_length=9)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
    ]
