# Generated by Django 2.2.7 on 2019-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('equipo', models.CharField(blank=True, max_length=30)),
                ('imagen_front', models.ImageField(null=True, upload_to='imagen/productos')),
                ('imagen_back', models.ImageField(null=True, upload_to='imagen/productos')),
            ],
        ),
    ]
