# Generated by Django 2.2.7 on 2019-11-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20191116_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('Staff', 'es Staff'), ('Usuario', 'es Usuario'))},
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
