# Generated by Django 2.2.6 on 2019-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('run', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono_contacto', models.CharField(max_length=9)),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
