# Generated by Django 2.2.6 on 2019-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0002_auto_20191031_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen/productos'),
        ),
    ]
