# Generated by Django 2.2.6 on 2019-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0003_auto_20191031_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen_back',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_front',
            field=models.ImageField(null=True, upload_to='imagen/productos'),
        ),
    ]
